/*
Lunch Money API - v2

Testing PlaidAccountsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package lunchmoney

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/juftin/lunchmoney-clients"
)

func Test_lunchmoney_PlaidAccountsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PlaidAccountsAPIService GetAllPlaidAccounts", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PlaidAccountsAPI.GetAllPlaidAccounts(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PlaidAccountsAPIService GetPlaidAccountById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id int32

		resp, httpRes, err := apiClient.PlaidAccountsAPI.GetPlaidAccountById(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PlaidAccountsAPIService TriggerPlaidAccountFetch", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.PlaidAccountsAPI.TriggerPlaidAccountFetch(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
