# yaml-language-server: $schema=https://www.taskfile.dev/schema.json

version: "3"
vars:
    CLIENT_NAME: "go"
    VERSION_PATH: go.additionalProperties.packageVersion
tasks:
    #######################################
    # Client Tasks
    #######################################
    install:
        desc: Install Project + Dev Dependencies
        cmds:
            - go get github.com/stretchr/testify/assert
            - go get golang.org/x/net/context
    #######################################
    publish:
        desc: Publish Package
        cmds:
            - exit 0
    #######################################
    test:
        desc: Run Tests
        cmds:
            - go test ./test -v
        deps:
            - install
    postprocess:
        desc: Post-Process Generated Code
        cmds:
            - exit 0
    #######################################
    version:
        desc: Set the Generator Config Version
        dir: "{{.ROOT_DIR}}"
        cmds:
            - cmd: |
                  jq --indent 4 \
                    --arg version "{{.VERSION}}" \
                    '."generator-cli".generators.{{.VERSION_PATH}} = $version' \
                    openapitools.json \
                    > openapitools.tmp.json && \
                    mv openapitools.tmp.json openapitools.json
    #######################################
    clean:
        desc: Clean Generated Client Code
        cmds:
            - cmd: rm -rf {{.ROOT_DIR}}/clients/{{.CLIENT_NAME}}
