/*
Lunch Money API - v2

### Introduction  Welcome to the Lunch Money v2 API reference. This is the **v2.11.0** spec.  The API is available at `https://api.lunchmoney.dev/v2`. Get your access token from the [Lunch Money developers page](https://my.lunchmoney.app/developers).   **Try it from these docs**  These docs are interactive — use **Test request** on any endpoint to call the API from this page. Choose a LIVE or MOCK service from the Server dropdown. Requests sent to `https://api.lunchmoney.dev/v2` can <span class=\"red-text\"><strong>change or delete</strong></span> your data and are <span class=\"red-text\"><strong>permanent</strong></span>. See the [Getting Started Guide](https://lunchmoney.dev/v2/getting-started) before using the live API.  **Static mock server**  Explore without risk to real data. Select `https://mock.lunchmoney.dev/v2` in the Server dropdown to work with static mock data. POST, PUT, and DELETE requests will return realistic responses, but do not change the mock data.   **Client Libraries & SDKs**  An official TypeScript SDK is available on [NPM](https://www.npmjs.com/package/@lunch-money/v2-api-spec) and [GitHub](https://github.com/lunch-money/lunch-money-js-v2). For Python or other languages, see [lunchmoney-clients](https://github.com/juftin/lunchmoney-clients) or generate a client from [this OpenAPI spec](/v2/openapi).  **Migrating from v1**  The v2 API is not backwards compatible with v1. See the [Migration Guide](https://lunchmoney.dev/v2/migration-guide) for details.  **Useful links** - [Getting Started Guide](https://lunchmoney.dev/v2/getting-started) - [v2 API Overview](https://lunchmoney.dev/v2/overview) - [Version History](https://lunchmoney.dev/v2/version-history) - [Migration Guide](https://lunchmoney.dev/v2/migration-guide) - [Rate Limits](https://lunchmoney.dev/v2/rate-limits)

API version: 2.11.0
Contact: devsupport@lunchmoney.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lunchmoney

import (
	"encoding/json"
	"time"
)

// checks if the UpdateCategoryRequestObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateCategoryRequestObject{}

// UpdateCategoryRequestObject struct for UpdateCategoryRequestObject
type UpdateCategoryRequestObject struct {
	// If set, updates the category name. Must be between 1 and 100 characters.
	Name *string `json:"name,omitempty"`
	// If set, updates the category description. Must not exceed 200 characters.
	Description NullableString `json:"description,omitempty"`
	// If set, determines whether transactions in this category are treated as income. (See [Category Properties](https://support.lunchmoney.app/setup/categories/category-properties) for details)
	IsIncome *bool `json:"is_income,omitempty"`
	// If set, determines whether transactions in this category are excluded from budgets. (See [Category Properties](https://support.lunchmoney.app/setup/categories/category-properties) for details)
	ExcludeFromBudget *bool `json:"exclude_from_budget,omitempty"`
	// If set, determines whether transactions in this category are excluded from totals. (See [Category Properties](https://support.lunchmoney.app/setup/categories/category-properties) for details)
	ExcludeFromTotals *bool `json:"exclude_from_totals,omitempty"`
	// If set, determines whether this category is archived.
	Archived *bool `json:"archived,omitempty"`
	// If set to the ID of an existing category group, and this category is not itself a category group, this category will be assigned to that group.
	GroupId NullableInt64 `json:"group_id,omitempty"`
	// This property is tolerated but cannot be changed. This API cannot be used to convert a category into a category group or vice versa.
	IsGroup NullableBool `json:"is_group,omitempty"`
	// List of existing category objects, existing category IDs, or names of new categories to add to the category group. This attribute should only be set when modifying an existing category group.<br> Categories or IDs must already exist and must not already belong to a category group. Categories that already belong to another category group will be moved. If strings are specified, they will be used as names for new categories added to the group. The request will fail if any provided name matches an existing category name.<br> You may mix full category objects, IDs, and new category names in the same request.
	Children []CreateCategoryRequestObjectChildrenInner `json:"children,omitempty"`
	// Position of the category on the categories page in the Lunch Money app. For categories within a category group, the order is relative to the other categories in the group.<br>While this property can be set via the API, it is generally managed by the user in the Lunch Money app.
	Order NullableInt32 `json:"order,omitempty"`
	// If `true`, the category is collapsed in the Lunch Money app.<br>While this property can be set via the API it is generally set by the user in the Lunch Money app.
	Collapsed NullableBool `json:"collapsed,omitempty"`
	// System defined unique identifier for the category. Ignored if set.
	Id *int64 `json:"id,omitempty"`
	// System set date and time of when the category was last archived (in the ISO 8601 extended format). Provide an ISO 8601 extended datetime or `null` to clear it.
	ArchivedAt NullableTime `json:"archived_at,omitempty"`
	// System set date and time of when the category was last updated (in the ISO 8601 extended format). Ignored if set.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// System set date and time of when the category was created (in the ISO 8601 extended format). Ignored if set.
	CreatedAt *time.Time `json:"created_at,omitempty"`
}

// NewUpdateCategoryRequestObject instantiates a new UpdateCategoryRequestObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateCategoryRequestObject() *UpdateCategoryRequestObject {
	this := UpdateCategoryRequestObject{}
	var isGroup bool = false
	this.IsGroup = *NewNullableBool(&isGroup)
	return &this
}

// NewUpdateCategoryRequestObjectWithDefaults instantiates a new UpdateCategoryRequestObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateCategoryRequestObjectWithDefaults() *UpdateCategoryRequestObject {
	this := UpdateCategoryRequestObject{}
	var isGroup bool = false
	this.IsGroup = *NewNullableBool(&isGroup)
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateCategoryRequestObject) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCategoryRequestObject) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateCategoryRequestObject) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateCategoryRequestObject) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateCategoryRequestObject) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateCategoryRequestObject) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdateCategoryRequestObject) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *UpdateCategoryRequestObject) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *UpdateCategoryRequestObject) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *UpdateCategoryRequestObject) UnsetDescription() {
	o.Description.Unset()
}

// GetIsIncome returns the IsIncome field value if set, zero value otherwise.
func (o *UpdateCategoryRequestObject) GetIsIncome() bool {
	if o == nil || IsNil(o.IsIncome) {
		var ret bool
		return ret
	}
	return *o.IsIncome
}

// GetIsIncomeOk returns a tuple with the IsIncome field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCategoryRequestObject) GetIsIncomeOk() (*bool, bool) {
	if o == nil || IsNil(o.IsIncome) {
		return nil, false
	}
	return o.IsIncome, true
}

// HasIsIncome returns a boolean if a field has been set.
func (o *UpdateCategoryRequestObject) HasIsIncome() bool {
	if o != nil && !IsNil(o.IsIncome) {
		return true
	}

	return false
}

// SetIsIncome gets a reference to the given bool and assigns it to the IsIncome field.
func (o *UpdateCategoryRequestObject) SetIsIncome(v bool) {
	o.IsIncome = &v
}

// GetExcludeFromBudget returns the ExcludeFromBudget field value if set, zero value otherwise.
func (o *UpdateCategoryRequestObject) GetExcludeFromBudget() bool {
	if o == nil || IsNil(o.ExcludeFromBudget) {
		var ret bool
		return ret
	}
	return *o.ExcludeFromBudget
}

// GetExcludeFromBudgetOk returns a tuple with the ExcludeFromBudget field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCategoryRequestObject) GetExcludeFromBudgetOk() (*bool, bool) {
	if o == nil || IsNil(o.ExcludeFromBudget) {
		return nil, false
	}
	return o.ExcludeFromBudget, true
}

// HasExcludeFromBudget returns a boolean if a field has been set.
func (o *UpdateCategoryRequestObject) HasExcludeFromBudget() bool {
	if o != nil && !IsNil(o.ExcludeFromBudget) {
		return true
	}

	return false
}

// SetExcludeFromBudget gets a reference to the given bool and assigns it to the ExcludeFromBudget field.
func (o *UpdateCategoryRequestObject) SetExcludeFromBudget(v bool) {
	o.ExcludeFromBudget = &v
}

// GetExcludeFromTotals returns the ExcludeFromTotals field value if set, zero value otherwise.
func (o *UpdateCategoryRequestObject) GetExcludeFromTotals() bool {
	if o == nil || IsNil(o.ExcludeFromTotals) {
		var ret bool
		return ret
	}
	return *o.ExcludeFromTotals
}

// GetExcludeFromTotalsOk returns a tuple with the ExcludeFromTotals field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCategoryRequestObject) GetExcludeFromTotalsOk() (*bool, bool) {
	if o == nil || IsNil(o.ExcludeFromTotals) {
		return nil, false
	}
	return o.ExcludeFromTotals, true
}

// HasExcludeFromTotals returns a boolean if a field has been set.
func (o *UpdateCategoryRequestObject) HasExcludeFromTotals() bool {
	if o != nil && !IsNil(o.ExcludeFromTotals) {
		return true
	}

	return false
}

// SetExcludeFromTotals gets a reference to the given bool and assigns it to the ExcludeFromTotals field.
func (o *UpdateCategoryRequestObject) SetExcludeFromTotals(v bool) {
	o.ExcludeFromTotals = &v
}

// GetArchived returns the Archived field value if set, zero value otherwise.
func (o *UpdateCategoryRequestObject) GetArchived() bool {
	if o == nil || IsNil(o.Archived) {
		var ret bool
		return ret
	}
	return *o.Archived
}

// GetArchivedOk returns a tuple with the Archived field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCategoryRequestObject) GetArchivedOk() (*bool, bool) {
	if o == nil || IsNil(o.Archived) {
		return nil, false
	}
	return o.Archived, true
}

// HasArchived returns a boolean if a field has been set.
func (o *UpdateCategoryRequestObject) HasArchived() bool {
	if o != nil && !IsNil(o.Archived) {
		return true
	}

	return false
}

// SetArchived gets a reference to the given bool and assigns it to the Archived field.
func (o *UpdateCategoryRequestObject) SetArchived(v bool) {
	o.Archived = &v
}

// GetGroupId returns the GroupId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateCategoryRequestObject) GetGroupId() int64 {
	if o == nil || IsNil(o.GroupId.Get()) {
		var ret int64
		return ret
	}
	return *o.GroupId.Get()
}

// GetGroupIdOk returns a tuple with the GroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateCategoryRequestObject) GetGroupIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.GroupId.Get(), o.GroupId.IsSet()
}

// HasGroupId returns a boolean if a field has been set.
func (o *UpdateCategoryRequestObject) HasGroupId() bool {
	if o != nil && o.GroupId.IsSet() {
		return true
	}

	return false
}

// SetGroupId gets a reference to the given NullableInt64 and assigns it to the GroupId field.
func (o *UpdateCategoryRequestObject) SetGroupId(v int64) {
	o.GroupId.Set(&v)
}
// SetGroupIdNil sets the value for GroupId to be an explicit nil
func (o *UpdateCategoryRequestObject) SetGroupIdNil() {
	o.GroupId.Set(nil)
}

// UnsetGroupId ensures that no value is present for GroupId, not even an explicit nil
func (o *UpdateCategoryRequestObject) UnsetGroupId() {
	o.GroupId.Unset()
}

// GetIsGroup returns the IsGroup field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateCategoryRequestObject) GetIsGroup() bool {
	if o == nil || IsNil(o.IsGroup.Get()) {
		var ret bool
		return ret
	}
	return *o.IsGroup.Get()
}

// GetIsGroupOk returns a tuple with the IsGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateCategoryRequestObject) GetIsGroupOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsGroup.Get(), o.IsGroup.IsSet()
}

// HasIsGroup returns a boolean if a field has been set.
func (o *UpdateCategoryRequestObject) HasIsGroup() bool {
	if o != nil && o.IsGroup.IsSet() {
		return true
	}

	return false
}

// SetIsGroup gets a reference to the given NullableBool and assigns it to the IsGroup field.
func (o *UpdateCategoryRequestObject) SetIsGroup(v bool) {
	o.IsGroup.Set(&v)
}
// SetIsGroupNil sets the value for IsGroup to be an explicit nil
func (o *UpdateCategoryRequestObject) SetIsGroupNil() {
	o.IsGroup.Set(nil)
}

// UnsetIsGroup ensures that no value is present for IsGroup, not even an explicit nil
func (o *UpdateCategoryRequestObject) UnsetIsGroup() {
	o.IsGroup.Unset()
}

// GetChildren returns the Children field value if set, zero value otherwise.
func (o *UpdateCategoryRequestObject) GetChildren() []CreateCategoryRequestObjectChildrenInner {
	if o == nil || IsNil(o.Children) {
		var ret []CreateCategoryRequestObjectChildrenInner
		return ret
	}
	return o.Children
}

// GetChildrenOk returns a tuple with the Children field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCategoryRequestObject) GetChildrenOk() ([]CreateCategoryRequestObjectChildrenInner, bool) {
	if o == nil || IsNil(o.Children) {
		return nil, false
	}
	return o.Children, true
}

// HasChildren returns a boolean if a field has been set.
func (o *UpdateCategoryRequestObject) HasChildren() bool {
	if o != nil && !IsNil(o.Children) {
		return true
	}

	return false
}

// SetChildren gets a reference to the given []CreateCategoryRequestObjectChildrenInner and assigns it to the Children field.
func (o *UpdateCategoryRequestObject) SetChildren(v []CreateCategoryRequestObjectChildrenInner) {
	o.Children = v
}

// GetOrder returns the Order field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateCategoryRequestObject) GetOrder() int32 {
	if o == nil || IsNil(o.Order.Get()) {
		var ret int32
		return ret
	}
	return *o.Order.Get()
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateCategoryRequestObject) GetOrderOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Order.Get(), o.Order.IsSet()
}

// HasOrder returns a boolean if a field has been set.
func (o *UpdateCategoryRequestObject) HasOrder() bool {
	if o != nil && o.Order.IsSet() {
		return true
	}

	return false
}

// SetOrder gets a reference to the given NullableInt32 and assigns it to the Order field.
func (o *UpdateCategoryRequestObject) SetOrder(v int32) {
	o.Order.Set(&v)
}
// SetOrderNil sets the value for Order to be an explicit nil
func (o *UpdateCategoryRequestObject) SetOrderNil() {
	o.Order.Set(nil)
}

// UnsetOrder ensures that no value is present for Order, not even an explicit nil
func (o *UpdateCategoryRequestObject) UnsetOrder() {
	o.Order.Unset()
}

// GetCollapsed returns the Collapsed field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateCategoryRequestObject) GetCollapsed() bool {
	if o == nil || IsNil(o.Collapsed.Get()) {
		var ret bool
		return ret
	}
	return *o.Collapsed.Get()
}

// GetCollapsedOk returns a tuple with the Collapsed field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateCategoryRequestObject) GetCollapsedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Collapsed.Get(), o.Collapsed.IsSet()
}

// HasCollapsed returns a boolean if a field has been set.
func (o *UpdateCategoryRequestObject) HasCollapsed() bool {
	if o != nil && o.Collapsed.IsSet() {
		return true
	}

	return false
}

// SetCollapsed gets a reference to the given NullableBool and assigns it to the Collapsed field.
func (o *UpdateCategoryRequestObject) SetCollapsed(v bool) {
	o.Collapsed.Set(&v)
}
// SetCollapsedNil sets the value for Collapsed to be an explicit nil
func (o *UpdateCategoryRequestObject) SetCollapsedNil() {
	o.Collapsed.Set(nil)
}

// UnsetCollapsed ensures that no value is present for Collapsed, not even an explicit nil
func (o *UpdateCategoryRequestObject) UnsetCollapsed() {
	o.Collapsed.Unset()
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *UpdateCategoryRequestObject) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCategoryRequestObject) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *UpdateCategoryRequestObject) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *UpdateCategoryRequestObject) SetId(v int64) {
	o.Id = &v
}

// GetArchivedAt returns the ArchivedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateCategoryRequestObject) GetArchivedAt() time.Time {
	if o == nil || IsNil(o.ArchivedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ArchivedAt.Get()
}

// GetArchivedAtOk returns a tuple with the ArchivedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateCategoryRequestObject) GetArchivedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ArchivedAt.Get(), o.ArchivedAt.IsSet()
}

// HasArchivedAt returns a boolean if a field has been set.
func (o *UpdateCategoryRequestObject) HasArchivedAt() bool {
	if o != nil && o.ArchivedAt.IsSet() {
		return true
	}

	return false
}

// SetArchivedAt gets a reference to the given NullableTime and assigns it to the ArchivedAt field.
func (o *UpdateCategoryRequestObject) SetArchivedAt(v time.Time) {
	o.ArchivedAt.Set(&v)
}
// SetArchivedAtNil sets the value for ArchivedAt to be an explicit nil
func (o *UpdateCategoryRequestObject) SetArchivedAtNil() {
	o.ArchivedAt.Set(nil)
}

// UnsetArchivedAt ensures that no value is present for ArchivedAt, not even an explicit nil
func (o *UpdateCategoryRequestObject) UnsetArchivedAt() {
	o.ArchivedAt.Unset()
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *UpdateCategoryRequestObject) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCategoryRequestObject) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *UpdateCategoryRequestObject) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *UpdateCategoryRequestObject) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *UpdateCategoryRequestObject) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCategoryRequestObject) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *UpdateCategoryRequestObject) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *UpdateCategoryRequestObject) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

func (o UpdateCategoryRequestObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateCategoryRequestObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if !IsNil(o.IsIncome) {
		toSerialize["is_income"] = o.IsIncome
	}
	if !IsNil(o.ExcludeFromBudget) {
		toSerialize["exclude_from_budget"] = o.ExcludeFromBudget
	}
	if !IsNil(o.ExcludeFromTotals) {
		toSerialize["exclude_from_totals"] = o.ExcludeFromTotals
	}
	if !IsNil(o.Archived) {
		toSerialize["archived"] = o.Archived
	}
	if o.GroupId.IsSet() {
		toSerialize["group_id"] = o.GroupId.Get()
	}
	if o.IsGroup.IsSet() {
		toSerialize["is_group"] = o.IsGroup.Get()
	}
	if !IsNil(o.Children) {
		toSerialize["children"] = o.Children
	}
	if o.Order.IsSet() {
		toSerialize["order"] = o.Order.Get()
	}
	if o.Collapsed.IsSet() {
		toSerialize["collapsed"] = o.Collapsed.Get()
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if o.ArchivedAt.IsSet() {
		toSerialize["archived_at"] = o.ArchivedAt.Get()
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	return toSerialize, nil
}

type NullableUpdateCategoryRequestObject struct {
	value *UpdateCategoryRequestObject
	isSet bool
}

func (v NullableUpdateCategoryRequestObject) Get() *UpdateCategoryRequestObject {
	return v.value
}

func (v *NullableUpdateCategoryRequestObject) Set(val *UpdateCategoryRequestObject) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateCategoryRequestObject) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateCategoryRequestObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateCategoryRequestObject(val *UpdateCategoryRequestObject) *NullableUpdateCategoryRequestObject {
	return &NullableUpdateCategoryRequestObject{value: val, isSet: true}
}

func (v NullableUpdateCategoryRequestObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateCategoryRequestObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


