/*
Lunch Money API - v2

### Introduction  Welcome to the Lunch Money v2 API reference. This is the **v2.11.0** spec.  The API is available at `https://api.lunchmoney.dev/v2`. Get your access token from the [Lunch Money developers page](https://my.lunchmoney.app/developers).   **Try it from these docs**  These docs are interactive — use **Test request** on any endpoint to call the API from this page. Choose a LIVE or MOCK service from the Server dropdown. Requests sent to `https://api.lunchmoney.dev/v2` can <span class=\"red-text\"><strong>change or delete</strong></span> your data and are <span class=\"red-text\"><strong>permanent</strong></span>. See the [Getting Started Guide](https://lunchmoney.dev/v2/getting-started) before using the live API.  **Static mock server**  Explore without risk to real data. Select `https://mock.lunchmoney.dev/v2` in the Server dropdown to work with static mock data. POST, PUT, and DELETE requests will return realistic responses, but do not change the mock data.   **Client Libraries & SDKs**  An official TypeScript SDK is available on [NPM](https://www.npmjs.com/package/@lunch-money/v2-api-spec) and [GitHub](https://github.com/lunch-money/lunch-money-js-v2). For Python or other languages, see [lunchmoney-clients](https://github.com/juftin/lunchmoney-clients) or generate a client from [this OpenAPI spec](/v2/openapi).  **Migrating from v1**  The v2 API is not backwards compatible with v1. See the [Migration Guide](https://lunchmoney.dev/v2/migration-guide) for details.  **Useful links** - [Getting Started Guide](https://lunchmoney.dev/v2/getting-started) - [v2 API Overview](https://lunchmoney.dev/v2/overview) - [Version History](https://lunchmoney.dev/v2/version-history) - [Migration Guide](https://lunchmoney.dev/v2/migration-guide) - [Rate Limits](https://lunchmoney.dev/v2/rate-limits)

API version: 2.11.0
Contact: devsupport@lunchmoney.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lunchmoney

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BudgetInvalidPeriodErrorObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BudgetInvalidPeriodErrorObject{}

// BudgetInvalidPeriodErrorObject Returned when the requested start_date is not a valid budget period start for the account.
type BudgetInvalidPeriodErrorObject struct {
	// Overall error message (e.g. Invalid Request)
	Message string `json:"message"`
	// The start_date value that was rejected
	RequestedStartDate string `json:"requested_start_date"`
	// The previous valid budget period start date before the requested date
	PreviousValidStartDate NullableString `json:"previous_valid_start_date,omitempty"`
	// The next valid budget period start date after the requested date
	NextValidStartDate NullableString `json:"next_valid_start_date,omitempty"`
	// Human-readable error message
	ErrMsg string `json:"errMsg"`
}

type _BudgetInvalidPeriodErrorObject BudgetInvalidPeriodErrorObject

// NewBudgetInvalidPeriodErrorObject instantiates a new BudgetInvalidPeriodErrorObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBudgetInvalidPeriodErrorObject(message string, requestedStartDate string, errMsg string) *BudgetInvalidPeriodErrorObject {
	this := BudgetInvalidPeriodErrorObject{}
	this.Message = message
	this.RequestedStartDate = requestedStartDate
	this.ErrMsg = errMsg
	return &this
}

// NewBudgetInvalidPeriodErrorObjectWithDefaults instantiates a new BudgetInvalidPeriodErrorObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBudgetInvalidPeriodErrorObjectWithDefaults() *BudgetInvalidPeriodErrorObject {
	this := BudgetInvalidPeriodErrorObject{}
	return &this
}

// GetMessage returns the Message field value
func (o *BudgetInvalidPeriodErrorObject) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *BudgetInvalidPeriodErrorObject) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *BudgetInvalidPeriodErrorObject) SetMessage(v string) {
	o.Message = v
}

// GetRequestedStartDate returns the RequestedStartDate field value
func (o *BudgetInvalidPeriodErrorObject) GetRequestedStartDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestedStartDate
}

// GetRequestedStartDateOk returns a tuple with the RequestedStartDate field value
// and a boolean to check if the value has been set.
func (o *BudgetInvalidPeriodErrorObject) GetRequestedStartDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestedStartDate, true
}

// SetRequestedStartDate sets field value
func (o *BudgetInvalidPeriodErrorObject) SetRequestedStartDate(v string) {
	o.RequestedStartDate = v
}

// GetPreviousValidStartDate returns the PreviousValidStartDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BudgetInvalidPeriodErrorObject) GetPreviousValidStartDate() string {
	if o == nil || IsNil(o.PreviousValidStartDate.Get()) {
		var ret string
		return ret
	}
	return *o.PreviousValidStartDate.Get()
}

// GetPreviousValidStartDateOk returns a tuple with the PreviousValidStartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BudgetInvalidPeriodErrorObject) GetPreviousValidStartDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PreviousValidStartDate.Get(), o.PreviousValidStartDate.IsSet()
}

// HasPreviousValidStartDate returns a boolean if a field has been set.
func (o *BudgetInvalidPeriodErrorObject) HasPreviousValidStartDate() bool {
	if o != nil && o.PreviousValidStartDate.IsSet() {
		return true
	}

	return false
}

// SetPreviousValidStartDate gets a reference to the given NullableString and assigns it to the PreviousValidStartDate field.
func (o *BudgetInvalidPeriodErrorObject) SetPreviousValidStartDate(v string) {
	o.PreviousValidStartDate.Set(&v)
}
// SetPreviousValidStartDateNil sets the value for PreviousValidStartDate to be an explicit nil
func (o *BudgetInvalidPeriodErrorObject) SetPreviousValidStartDateNil() {
	o.PreviousValidStartDate.Set(nil)
}

// UnsetPreviousValidStartDate ensures that no value is present for PreviousValidStartDate, not even an explicit nil
func (o *BudgetInvalidPeriodErrorObject) UnsetPreviousValidStartDate() {
	o.PreviousValidStartDate.Unset()
}

// GetNextValidStartDate returns the NextValidStartDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BudgetInvalidPeriodErrorObject) GetNextValidStartDate() string {
	if o == nil || IsNil(o.NextValidStartDate.Get()) {
		var ret string
		return ret
	}
	return *o.NextValidStartDate.Get()
}

// GetNextValidStartDateOk returns a tuple with the NextValidStartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BudgetInvalidPeriodErrorObject) GetNextValidStartDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextValidStartDate.Get(), o.NextValidStartDate.IsSet()
}

// HasNextValidStartDate returns a boolean if a field has been set.
func (o *BudgetInvalidPeriodErrorObject) HasNextValidStartDate() bool {
	if o != nil && o.NextValidStartDate.IsSet() {
		return true
	}

	return false
}

// SetNextValidStartDate gets a reference to the given NullableString and assigns it to the NextValidStartDate field.
func (o *BudgetInvalidPeriodErrorObject) SetNextValidStartDate(v string) {
	o.NextValidStartDate.Set(&v)
}
// SetNextValidStartDateNil sets the value for NextValidStartDate to be an explicit nil
func (o *BudgetInvalidPeriodErrorObject) SetNextValidStartDateNil() {
	o.NextValidStartDate.Set(nil)
}

// UnsetNextValidStartDate ensures that no value is present for NextValidStartDate, not even an explicit nil
func (o *BudgetInvalidPeriodErrorObject) UnsetNextValidStartDate() {
	o.NextValidStartDate.Unset()
}

// GetErrMsg returns the ErrMsg field value
func (o *BudgetInvalidPeriodErrorObject) GetErrMsg() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ErrMsg
}

// GetErrMsgOk returns a tuple with the ErrMsg field value
// and a boolean to check if the value has been set.
func (o *BudgetInvalidPeriodErrorObject) GetErrMsgOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ErrMsg, true
}

// SetErrMsg sets field value
func (o *BudgetInvalidPeriodErrorObject) SetErrMsg(v string) {
	o.ErrMsg = v
}

func (o BudgetInvalidPeriodErrorObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BudgetInvalidPeriodErrorObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["requested_start_date"] = o.RequestedStartDate
	if o.PreviousValidStartDate.IsSet() {
		toSerialize["previous_valid_start_date"] = o.PreviousValidStartDate.Get()
	}
	if o.NextValidStartDate.IsSet() {
		toSerialize["next_valid_start_date"] = o.NextValidStartDate.Get()
	}
	toSerialize["errMsg"] = o.ErrMsg
	return toSerialize, nil
}

func (o *BudgetInvalidPeriodErrorObject) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"requested_start_date",
		"errMsg",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBudgetInvalidPeriodErrorObject := _BudgetInvalidPeriodErrorObject{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBudgetInvalidPeriodErrorObject)

	if err != nil {
		return err
	}

	*o = BudgetInvalidPeriodErrorObject(varBudgetInvalidPeriodErrorObject)

	return err
}

type NullableBudgetInvalidPeriodErrorObject struct {
	value *BudgetInvalidPeriodErrorObject
	isSet bool
}

func (v NullableBudgetInvalidPeriodErrorObject) Get() *BudgetInvalidPeriodErrorObject {
	return v.value
}

func (v *NullableBudgetInvalidPeriodErrorObject) Set(val *BudgetInvalidPeriodErrorObject) {
	v.value = val
	v.isSet = true
}

func (v NullableBudgetInvalidPeriodErrorObject) IsSet() bool {
	return v.isSet
}

func (v *NullableBudgetInvalidPeriodErrorObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBudgetInvalidPeriodErrorObject(val *BudgetInvalidPeriodErrorObject) *NullableBudgetInvalidPeriodErrorObject {
	return &NullableBudgetInvalidPeriodErrorObject{value: val, isSet: true}
}

func (v NullableBudgetInvalidPeriodErrorObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBudgetInvalidPeriodErrorObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


