/*
Lunch Money API - v2

Welcome to the Lunch Money v2 API. The API is available at `https://api.lunchmoney.dev/v2`. Get your access token from the [Lunch Money developers page](https://my.lunchmoney.app/developers).  ### Introduction  <span class=\"red-text\"><strong>The v2 API is in open alpha and is still subject to change. Use the mock server or a test budget when getting started.</strong></span>  **Static Mock Server**  Explore the API without an access token or risk to real data. Select **\"Static Mock v2 Lunch Money API Server\"** from the Server dropdown, then set your Bearer token to any string with 11 or more characters.  **Migrating from v1**  The v2 API is not backwards compatible with v1. See the [Migration Guide](https://alpha.lunchmoney.dev/v2/migration-guide) for details.  **Useful links** - [Developer Portal](https://lunchmoney.dev/v2/introduction) - [Getting Started Guide](https://lunchmoney.dev/v2/getting-started) - [v2 API Overview](https://lunchmoney.dev/v2/overview) - [v2 API Changelog](https://lunchmoney.dev/v2/changelog) - [Migration Guide](https://lunchmoney.dev/v2/migration-guide) - [Rate Limits](https://lunchmoney.dev/v2/rate-limits)

API version: 2.9.3
Contact: devsupport@lunchmoney.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lunchmoney

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// InsertTransactionObjectAmount - Numeric value of amount without currency symbol. i.e. $4.25 should be denoted as 4.25. May be a string or a number in double format. Positive values indicate a debit transaction, negative values indicate a credit transaction.
type InsertTransactionObjectAmount struct {
	Float64 *float64
	String *string
}

// float64AsInsertTransactionObjectAmount is a convenience function that returns float64 wrapped in InsertTransactionObjectAmount
func Float64AsInsertTransactionObjectAmount(v *float64) InsertTransactionObjectAmount {
	return InsertTransactionObjectAmount{
		Float64: v,
	}
}

// stringAsInsertTransactionObjectAmount is a convenience function that returns string wrapped in InsertTransactionObjectAmount
func StringAsInsertTransactionObjectAmount(v *string) InsertTransactionObjectAmount {
	return InsertTransactionObjectAmount{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *InsertTransactionObjectAmount) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Float64
	err = newStrictDecoder(data).Decode(&dst.Float64)
	if err == nil {
		jsonFloat64, _ := json.Marshal(dst.Float64)
		if string(jsonFloat64) == "{}" { // empty struct
			dst.Float64 = nil
		} else {
			if err = validator.Validate(dst.Float64); err != nil {
				dst.Float64 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Float64 = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Float64 = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(InsertTransactionObjectAmount)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(InsertTransactionObjectAmount)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src InsertTransactionObjectAmount) MarshalJSON() ([]byte, error) {
	if src.Float64 != nil {
		return json.Marshal(&src.Float64)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *InsertTransactionObjectAmount) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.Float64 != nil {
		return obj.Float64
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj InsertTransactionObjectAmount) GetActualInstanceValue() (interface{}) {
	if obj.Float64 != nil {
		return *obj.Float64
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableInsertTransactionObjectAmount struct {
	value *InsertTransactionObjectAmount
	isSet bool
}

func (v NullableInsertTransactionObjectAmount) Get() *InsertTransactionObjectAmount {
	return v.value
}

func (v *NullableInsertTransactionObjectAmount) Set(val *InsertTransactionObjectAmount) {
	v.value = val
	v.isSet = true
}

func (v NullableInsertTransactionObjectAmount) IsSet() bool {
	return v.isSet
}

func (v *NullableInsertTransactionObjectAmount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInsertTransactionObjectAmount(val *InsertTransactionObjectAmount) *NullableInsertTransactionObjectAmount {
	return &NullableInsertTransactionObjectAmount{value: val, isSet: true}
}

func (v NullableInsertTransactionObjectAmount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInsertTransactionObjectAmount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


