/*
Lunch Money API - v2

### Introduction  Welcome to the Lunch Money v2 API reference. This is the **v2.11.0** spec.  The API is available at `https://api.lunchmoney.dev/v2`. Get your access token from the [Lunch Money developers page](https://my.lunchmoney.app/developers).   **Try it from these docs**  These docs are interactive — use **Test request** on any endpoint to call the API from this page. Choose a LIVE or MOCK service from the Server dropdown. Requests sent to `https://api.lunchmoney.dev/v2` can <span class=\"red-text\"><strong>change or delete</strong></span> your data and are <span class=\"red-text\"><strong>permanent</strong></span>. See the [Getting Started Guide](https://lunchmoney.dev/v2/getting-started) before using the live API.  **Static mock server**  Explore without risk to real data. Select `https://mock.lunchmoney.dev/v2` in the Server dropdown to work with static mock data. POST, PUT, and DELETE requests will return realistic responses, but do not change the mock data.   **Client Libraries & SDKs**  An official TypeScript SDK is available on [NPM](https://www.npmjs.com/package/@lunch-money/v2-api-spec) and [GitHub](https://github.com/lunch-money/lunch-money-js-v2). For Python or other languages, see [lunchmoney-clients](https://github.com/juftin/lunchmoney-clients) or generate a client from [this OpenAPI spec](/v2/openapi).  **Migrating from v1**  The v2 API is not backwards compatible with v1. See the [Migration Guide](https://lunchmoney.dev/v2/migration-guide) for details.  **Useful links** - [Getting Started Guide](https://lunchmoney.dev/v2/getting-started) - [v2 API Overview](https://lunchmoney.dev/v2/overview) - [Version History](https://lunchmoney.dev/v2/version-history) - [Migration Guide](https://lunchmoney.dev/v2/migration-guide) - [Rate Limits](https://lunchmoney.dev/v2/rate-limits)

API version: 2.11.0
Contact: devsupport@lunchmoney.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lunchmoney

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SummaryResponseObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SummaryResponseObject{}

// SummaryResponseObject Budget summary for the requested range
type SummaryResponseObject struct {
	// `true` if start_date and end_date are aligned with the user's budget period setting; `false` otherwise.<p> When the response is not aligned, category `totals` will not include values for the `budgeted` and `available` properties, so aligned responses are usually preferred.<p> If unsure how to set an aligned date range, set a range of at least one month and set the `include_occurrences` parameter to `true`. Then examine the objects in the `occurrences` array for the first category to find start and end dates that will produce aligned responses.  Setting `include_past_budget_dates` to `true` will add the three budget periods prior to the range in the `occurrences` array.
	Aligned bool `json:"aligned"`
	Categories []SummaryCategoryObject `json:"categories"`
	Totals *SummaryTotalsObject `json:"totals,omitempty"`
	RolloverPool *SummaryRolloverPoolObject `json:"rollover_pool,omitempty"`
}

type _SummaryResponseObject SummaryResponseObject

// NewSummaryResponseObject instantiates a new SummaryResponseObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSummaryResponseObject(aligned bool, categories []SummaryCategoryObject) *SummaryResponseObject {
	this := SummaryResponseObject{}
	this.Aligned = aligned
	this.Categories = categories
	return &this
}

// NewSummaryResponseObjectWithDefaults instantiates a new SummaryResponseObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSummaryResponseObjectWithDefaults() *SummaryResponseObject {
	this := SummaryResponseObject{}
	return &this
}

// GetAligned returns the Aligned field value
func (o *SummaryResponseObject) GetAligned() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Aligned
}

// GetAlignedOk returns a tuple with the Aligned field value
// and a boolean to check if the value has been set.
func (o *SummaryResponseObject) GetAlignedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Aligned, true
}

// SetAligned sets field value
func (o *SummaryResponseObject) SetAligned(v bool) {
	o.Aligned = v
}

// GetCategories returns the Categories field value
func (o *SummaryResponseObject) GetCategories() []SummaryCategoryObject {
	if o == nil {
		var ret []SummaryCategoryObject
		return ret
	}

	return o.Categories
}

// GetCategoriesOk returns a tuple with the Categories field value
// and a boolean to check if the value has been set.
func (o *SummaryResponseObject) GetCategoriesOk() ([]SummaryCategoryObject, bool) {
	if o == nil {
		return nil, false
	}
	return o.Categories, true
}

// SetCategories sets field value
func (o *SummaryResponseObject) SetCategories(v []SummaryCategoryObject) {
	o.Categories = v
}

// GetTotals returns the Totals field value if set, zero value otherwise.
func (o *SummaryResponseObject) GetTotals() SummaryTotalsObject {
	if o == nil || IsNil(o.Totals) {
		var ret SummaryTotalsObject
		return ret
	}
	return *o.Totals
}

// GetTotalsOk returns a tuple with the Totals field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryResponseObject) GetTotalsOk() (*SummaryTotalsObject, bool) {
	if o == nil || IsNil(o.Totals) {
		return nil, false
	}
	return o.Totals, true
}

// HasTotals returns a boolean if a field has been set.
func (o *SummaryResponseObject) HasTotals() bool {
	if o != nil && !IsNil(o.Totals) {
		return true
	}

	return false
}

// SetTotals gets a reference to the given SummaryTotalsObject and assigns it to the Totals field.
func (o *SummaryResponseObject) SetTotals(v SummaryTotalsObject) {
	o.Totals = &v
}

// GetRolloverPool returns the RolloverPool field value if set, zero value otherwise.
func (o *SummaryResponseObject) GetRolloverPool() SummaryRolloverPoolObject {
	if o == nil || IsNil(o.RolloverPool) {
		var ret SummaryRolloverPoolObject
		return ret
	}
	return *o.RolloverPool
}

// GetRolloverPoolOk returns a tuple with the RolloverPool field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryResponseObject) GetRolloverPoolOk() (*SummaryRolloverPoolObject, bool) {
	if o == nil || IsNil(o.RolloverPool) {
		return nil, false
	}
	return o.RolloverPool, true
}

// HasRolloverPool returns a boolean if a field has been set.
func (o *SummaryResponseObject) HasRolloverPool() bool {
	if o != nil && !IsNil(o.RolloverPool) {
		return true
	}

	return false
}

// SetRolloverPool gets a reference to the given SummaryRolloverPoolObject and assigns it to the RolloverPool field.
func (o *SummaryResponseObject) SetRolloverPool(v SummaryRolloverPoolObject) {
	o.RolloverPool = &v
}

func (o SummaryResponseObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SummaryResponseObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["aligned"] = o.Aligned
	toSerialize["categories"] = o.Categories
	if !IsNil(o.Totals) {
		toSerialize["totals"] = o.Totals
	}
	if !IsNil(o.RolloverPool) {
		toSerialize["rollover_pool"] = o.RolloverPool
	}
	return toSerialize, nil
}

func (o *SummaryResponseObject) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"aligned",
		"categories",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSummaryResponseObject := _SummaryResponseObject{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSummaryResponseObject)

	if err != nil {
		return err
	}

	*o = SummaryResponseObject(varSummaryResponseObject)

	return err
}

type NullableSummaryResponseObject struct {
	value *SummaryResponseObject
	isSet bool
}

func (v NullableSummaryResponseObject) Get() *SummaryResponseObject {
	return v.value
}

func (v *NullableSummaryResponseObject) Set(val *SummaryResponseObject) {
	v.value = val
	v.isSet = true
}

func (v NullableSummaryResponseObject) IsSet() bool {
	return v.isSet
}

func (v *NullableSummaryResponseObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSummaryResponseObject(val *SummaryResponseObject) *NullableSummaryResponseObject {
	return &NullableSummaryResponseObject{value: val, isSet: true}
}

func (v NullableSummaryResponseObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSummaryResponseObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


