/*
Lunch Money API - v2

### Introduction  Welcome to the Lunch Money v2 API reference. This is the **v2.11.0** spec.  The API is available at `https://api.lunchmoney.dev/v2`. Get your access token from the [Lunch Money developers page](https://my.lunchmoney.app/developers).   **Try it from these docs**  These docs are interactive — use **Test request** on any endpoint to call the API from this page. Choose a LIVE or MOCK service from the Server dropdown. Requests sent to `https://api.lunchmoney.dev/v2` can <span class=\"red-text\"><strong>change or delete</strong></span> your data and are <span class=\"red-text\"><strong>permanent</strong></span>. See the [Getting Started Guide](https://lunchmoney.dev/v2/getting-started) before using the live API.  **Static mock server**  Explore without risk to real data. Select `https://mock.lunchmoney.dev/v2` in the Server dropdown to work with static mock data. POST, PUT, and DELETE requests will return realistic responses, but do not change the mock data.   **Client Libraries & SDKs**  An official TypeScript SDK is available on [NPM](https://www.npmjs.com/package/@lunch-money/v2-api-spec) and [GitHub](https://github.com/lunch-money/lunch-money-js-v2). For Python or other languages, see [lunchmoney-clients](https://github.com/juftin/lunchmoney-clients) or generate a client from [this OpenAPI spec](/v2/openapi).  **Migrating from v1**  The v2 API is not backwards compatible with v1. See the [Migration Guide](https://lunchmoney.dev/v2/migration-guide) for details.  **Useful links** - [Getting Started Guide](https://lunchmoney.dev/v2/getting-started) - [v2 API Overview](https://lunchmoney.dev/v2/overview) - [Version History](https://lunchmoney.dev/v2/version-history) - [Migration Guide](https://lunchmoney.dev/v2/migration-guide) - [Rate Limits](https://lunchmoney.dev/v2/rate-limits)

API version: 2.11.0
Contact: devsupport@lunchmoney.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lunchmoney

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the CategoryObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CategoryObject{}

// CategoryObject struct for CategoryObject
type CategoryObject struct {
	// System defined unique ID for the category
	Id int32 `json:"id"`
	// Name of the category
	Name string `json:"name"`
	// Category description, or `null` if none is set
	Description NullableString `json:"description"`
	// If `true`, transactions in this category are treated as income. (See [Category Properties](https://support.lunchmoney.app/setup/categories/category-properties) for details)
	IsIncome bool `json:"is_income"`
	// If `true`, transactions in this category are excluded from the budget. (See [Category Properties](https://support.lunchmoney.app/setup/categories/category-properties) for details)
	ExcludeFromBudget bool `json:"exclude_from_budget"`
	// If `true`, transactions in this category are excluded from totals. (See [Category Properties](https://support.lunchmoney.app/setup/categories/category-properties) for details)
	ExcludeFromTotals bool `json:"exclude_from_totals"`
	// Date and time the category was last updated (in the ISO 8601 extended format).
	UpdatedAt time.Time `json:"updated_at"`
	// Date and time of when the category was created (ISO 8601 extended format).
	CreatedAt time.Time `json:"created_at"`
	// ID of the category group this category belongs to, or `null` if it does not belong to a group, or is itself a group.
	GroupId NullableInt64 `json:"group_id"`
	// If `true`, this category is created as a category group
	IsGroup bool `json:"is_group"`
	// For category groups, contains details about the categories in the group. These objects are similar to Category Objects but the `is_group` property will always be `false`, and there will be no `children` attribute.
	Children []ChildCategoryObject `json:"children,omitempty"`
	// If true, the category is archived and hidden in relevant areas of the Lunch Money app.
	Archived bool `json:"archived"`
	// Date and time the category was last archived ( ISO 8601 extended format).
	ArchivedAt NullableTime `json:"archived_at"`
	// Position of the category on the categories page in the Lunch Money app. For grouped categories, the order is relative to others in the same group.<br> Categories with `order: null` are shown alphabetically before ordered categories
	Order NullableInt32 `json:"order"`
	// If `true`, the category appears collapsed in the Lunch Money app
	Collapsed bool `json:"collapsed"`
}

type _CategoryObject CategoryObject

// NewCategoryObject instantiates a new CategoryObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCategoryObject(id int32, name string, description NullableString, isIncome bool, excludeFromBudget bool, excludeFromTotals bool, updatedAt time.Time, createdAt time.Time, groupId NullableInt64, isGroup bool, archived bool, archivedAt NullableTime, order NullableInt32, collapsed bool) *CategoryObject {
	this := CategoryObject{}
	this.Id = id
	this.Name = name
	this.Description = description
	this.IsIncome = isIncome
	this.ExcludeFromBudget = excludeFromBudget
	this.ExcludeFromTotals = excludeFromTotals
	this.UpdatedAt = updatedAt
	this.CreatedAt = createdAt
	this.GroupId = groupId
	this.IsGroup = isGroup
	this.Archived = archived
	this.ArchivedAt = archivedAt
	this.Order = order
	this.Collapsed = collapsed
	return &this
}

// NewCategoryObjectWithDefaults instantiates a new CategoryObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCategoryObjectWithDefaults() *CategoryObject {
	this := CategoryObject{}
	var collapsed bool = false
	this.Collapsed = collapsed
	return &this
}

// GetId returns the Id field value
func (o *CategoryObject) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CategoryObject) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CategoryObject) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value
func (o *CategoryObject) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CategoryObject) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CategoryObject) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
// If the value is explicit nil, the zero value for string will be returned
func (o *CategoryObject) GetDescription() string {
	if o == nil || o.Description.Get() == nil {
		var ret string
		return ret
	}

	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CategoryObject) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// SetDescription sets field value
func (o *CategoryObject) SetDescription(v string) {
	o.Description.Set(&v)
}

// GetIsIncome returns the IsIncome field value
func (o *CategoryObject) GetIsIncome() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsIncome
}

// GetIsIncomeOk returns a tuple with the IsIncome field value
// and a boolean to check if the value has been set.
func (o *CategoryObject) GetIsIncomeOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsIncome, true
}

// SetIsIncome sets field value
func (o *CategoryObject) SetIsIncome(v bool) {
	o.IsIncome = v
}

// GetExcludeFromBudget returns the ExcludeFromBudget field value
func (o *CategoryObject) GetExcludeFromBudget() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ExcludeFromBudget
}

// GetExcludeFromBudgetOk returns a tuple with the ExcludeFromBudget field value
// and a boolean to check if the value has been set.
func (o *CategoryObject) GetExcludeFromBudgetOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExcludeFromBudget, true
}

// SetExcludeFromBudget sets field value
func (o *CategoryObject) SetExcludeFromBudget(v bool) {
	o.ExcludeFromBudget = v
}

// GetExcludeFromTotals returns the ExcludeFromTotals field value
func (o *CategoryObject) GetExcludeFromTotals() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ExcludeFromTotals
}

// GetExcludeFromTotalsOk returns a tuple with the ExcludeFromTotals field value
// and a boolean to check if the value has been set.
func (o *CategoryObject) GetExcludeFromTotalsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExcludeFromTotals, true
}

// SetExcludeFromTotals sets field value
func (o *CategoryObject) SetExcludeFromTotals(v bool) {
	o.ExcludeFromTotals = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *CategoryObject) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *CategoryObject) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *CategoryObject) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *CategoryObject) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *CategoryObject) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *CategoryObject) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetGroupId returns the GroupId field value
// If the value is explicit nil, the zero value for int64 will be returned
func (o *CategoryObject) GetGroupId() int64 {
	if o == nil || o.GroupId.Get() == nil {
		var ret int64
		return ret
	}

	return *o.GroupId.Get()
}

// GetGroupIdOk returns a tuple with the GroupId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CategoryObject) GetGroupIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.GroupId.Get(), o.GroupId.IsSet()
}

// SetGroupId sets field value
func (o *CategoryObject) SetGroupId(v int64) {
	o.GroupId.Set(&v)
}

// GetIsGroup returns the IsGroup field value
func (o *CategoryObject) GetIsGroup() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsGroup
}

// GetIsGroupOk returns a tuple with the IsGroup field value
// and a boolean to check if the value has been set.
func (o *CategoryObject) GetIsGroupOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsGroup, true
}

// SetIsGroup sets field value
func (o *CategoryObject) SetIsGroup(v bool) {
	o.IsGroup = v
}

// GetChildren returns the Children field value if set, zero value otherwise.
func (o *CategoryObject) GetChildren() []ChildCategoryObject {
	if o == nil || IsNil(o.Children) {
		var ret []ChildCategoryObject
		return ret
	}
	return o.Children
}

// GetChildrenOk returns a tuple with the Children field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CategoryObject) GetChildrenOk() ([]ChildCategoryObject, bool) {
	if o == nil || IsNil(o.Children) {
		return nil, false
	}
	return o.Children, true
}

// HasChildren returns a boolean if a field has been set.
func (o *CategoryObject) HasChildren() bool {
	if o != nil && !IsNil(o.Children) {
		return true
	}

	return false
}

// SetChildren gets a reference to the given []ChildCategoryObject and assigns it to the Children field.
func (o *CategoryObject) SetChildren(v []ChildCategoryObject) {
	o.Children = v
}

// GetArchived returns the Archived field value
func (o *CategoryObject) GetArchived() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Archived
}

// GetArchivedOk returns a tuple with the Archived field value
// and a boolean to check if the value has been set.
func (o *CategoryObject) GetArchivedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Archived, true
}

// SetArchived sets field value
func (o *CategoryObject) SetArchived(v bool) {
	o.Archived = v
}

// GetArchivedAt returns the ArchivedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *CategoryObject) GetArchivedAt() time.Time {
	if o == nil || o.ArchivedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.ArchivedAt.Get()
}

// GetArchivedAtOk returns a tuple with the ArchivedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CategoryObject) GetArchivedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ArchivedAt.Get(), o.ArchivedAt.IsSet()
}

// SetArchivedAt sets field value
func (o *CategoryObject) SetArchivedAt(v time.Time) {
	o.ArchivedAt.Set(&v)
}

// GetOrder returns the Order field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *CategoryObject) GetOrder() int32 {
	if o == nil || o.Order.Get() == nil {
		var ret int32
		return ret
	}

	return *o.Order.Get()
}

// GetOrderOk returns a tuple with the Order field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CategoryObject) GetOrderOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Order.Get(), o.Order.IsSet()
}

// SetOrder sets field value
func (o *CategoryObject) SetOrder(v int32) {
	o.Order.Set(&v)
}

// GetCollapsed returns the Collapsed field value
func (o *CategoryObject) GetCollapsed() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Collapsed
}

// GetCollapsedOk returns a tuple with the Collapsed field value
// and a boolean to check if the value has been set.
func (o *CategoryObject) GetCollapsedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Collapsed, true
}

// SetCollapsed sets field value
func (o *CategoryObject) SetCollapsed(v bool) {
	o.Collapsed = v
}

func (o CategoryObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CategoryObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description.Get()
	toSerialize["is_income"] = o.IsIncome
	toSerialize["exclude_from_budget"] = o.ExcludeFromBudget
	toSerialize["exclude_from_totals"] = o.ExcludeFromTotals
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["group_id"] = o.GroupId.Get()
	toSerialize["is_group"] = o.IsGroup
	if !IsNil(o.Children) {
		toSerialize["children"] = o.Children
	}
	toSerialize["archived"] = o.Archived
	toSerialize["archived_at"] = o.ArchivedAt.Get()
	toSerialize["order"] = o.Order.Get()
	toSerialize["collapsed"] = o.Collapsed
	return toSerialize, nil
}

func (o *CategoryObject) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"description",
		"is_income",
		"exclude_from_budget",
		"exclude_from_totals",
		"updated_at",
		"created_at",
		"group_id",
		"is_group",
		"archived",
		"archived_at",
		"order",
		"collapsed",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCategoryObject := _CategoryObject{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCategoryObject)

	if err != nil {
		return err
	}

	*o = CategoryObject(varCategoryObject)

	return err
}

type NullableCategoryObject struct {
	value *CategoryObject
	isSet bool
}

func (v NullableCategoryObject) Get() *CategoryObject {
	return v.value
}

func (v *NullableCategoryObject) Set(val *CategoryObject) {
	v.value = val
	v.isSet = true
}

func (v NullableCategoryObject) IsSet() bool {
	return v.isSet
}

func (v *NullableCategoryObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCategoryObject(val *CategoryObject) *NullableCategoryObject {
	return &NullableCategoryObject{value: val, isSet: true}
}

func (v NullableCategoryObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCategoryObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


