/*
Lunch Money API - v2

### Introduction  Welcome to the Lunch Money v2 API reference. This is the **v2.11.0** spec.  The API is available at `https://api.lunchmoney.dev/v2`. Get your access token from the [Lunch Money developers page](https://my.lunchmoney.app/developers).   **Try it from these docs**  These docs are interactive — use **Test request** on any endpoint to call the API from this page. Choose a LIVE or MOCK service from the Server dropdown. Requests sent to `https://api.lunchmoney.dev/v2` can <span class=\"red-text\"><strong>change or delete</strong></span> your data and are <span class=\"red-text\"><strong>permanent</strong></span>. See the [Getting Started Guide](https://lunchmoney.dev/v2/getting-started) before using the live API.  **Static mock server**  Explore without risk to real data. Select `https://mock.lunchmoney.dev/v2` in the Server dropdown to work with static mock data. POST, PUT, and DELETE requests will return realistic responses, but do not change the mock data.   **Client Libraries & SDKs**  An official TypeScript SDK is available on [NPM](https://www.npmjs.com/package/@lunch-money/v2-api-spec) and [GitHub](https://github.com/lunch-money/lunch-money-js-v2). For Python or other languages, see [lunchmoney-clients](https://github.com/juftin/lunchmoney-clients) or generate a client from [this OpenAPI spec](/v2/openapi).  **Migrating from v1**  The v2 API is not backwards compatible with v1. See the [Migration Guide](https://lunchmoney.dev/v2/migration-guide) for details.  **Useful links** - [Getting Started Guide](https://lunchmoney.dev/v2/getting-started) - [v2 API Overview](https://lunchmoney.dev/v2/overview) - [Version History](https://lunchmoney.dev/v2/version-history) - [Migration Guide](https://lunchmoney.dev/v2/migration-guide) - [Rate Limits](https://lunchmoney.dev/v2/rate-limits)

API version: 2.11.0
Contact: devsupport@lunchmoney.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lunchmoney

import (
	"encoding/json"
)

// checks if the GetAllPlaidAccounts200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAllPlaidAccounts200Response{}

// GetAllPlaidAccounts200Response struct for GetAllPlaidAccounts200Response
type GetAllPlaidAccounts200Response struct {
	PlaidAccounts []PlaidAccountObject `json:"plaid_accounts,omitempty"`
}

// NewGetAllPlaidAccounts200Response instantiates a new GetAllPlaidAccounts200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAllPlaidAccounts200Response() *GetAllPlaidAccounts200Response {
	this := GetAllPlaidAccounts200Response{}
	return &this
}

// NewGetAllPlaidAccounts200ResponseWithDefaults instantiates a new GetAllPlaidAccounts200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAllPlaidAccounts200ResponseWithDefaults() *GetAllPlaidAccounts200Response {
	this := GetAllPlaidAccounts200Response{}
	return &this
}

// GetPlaidAccounts returns the PlaidAccounts field value if set, zero value otherwise.
func (o *GetAllPlaidAccounts200Response) GetPlaidAccounts() []PlaidAccountObject {
	if o == nil || IsNil(o.PlaidAccounts) {
		var ret []PlaidAccountObject
		return ret
	}
	return o.PlaidAccounts
}

// GetPlaidAccountsOk returns a tuple with the PlaidAccounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllPlaidAccounts200Response) GetPlaidAccountsOk() ([]PlaidAccountObject, bool) {
	if o == nil || IsNil(o.PlaidAccounts) {
		return nil, false
	}
	return o.PlaidAccounts, true
}

// HasPlaidAccounts returns a boolean if a field has been set.
func (o *GetAllPlaidAccounts200Response) HasPlaidAccounts() bool {
	if o != nil && !IsNil(o.PlaidAccounts) {
		return true
	}

	return false
}

// SetPlaidAccounts gets a reference to the given []PlaidAccountObject and assigns it to the PlaidAccounts field.
func (o *GetAllPlaidAccounts200Response) SetPlaidAccounts(v []PlaidAccountObject) {
	o.PlaidAccounts = v
}

func (o GetAllPlaidAccounts200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAllPlaidAccounts200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PlaidAccounts) {
		toSerialize["plaid_accounts"] = o.PlaidAccounts
	}
	return toSerialize, nil
}

type NullableGetAllPlaidAccounts200Response struct {
	value *GetAllPlaidAccounts200Response
	isSet bool
}

func (v NullableGetAllPlaidAccounts200Response) Get() *GetAllPlaidAccounts200Response {
	return v.value
}

func (v *NullableGetAllPlaidAccounts200Response) Set(val *GetAllPlaidAccounts200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAllPlaidAccounts200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAllPlaidAccounts200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAllPlaidAccounts200Response(val *GetAllPlaidAccounts200Response) *NullableGetAllPlaidAccounts200Response {
	return &NullableGetAllPlaidAccounts200Response{value: val, isSet: true}
}

func (v NullableGetAllPlaidAccounts200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAllPlaidAccounts200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


