/*
Lunch Money API - v2

### Introduction  Welcome to the Lunch Money v2 API reference. This is the **v2.11.0** spec.  The API is available at `https://api.lunchmoney.dev/v2`. Get your access token from the [Lunch Money developers page](https://my.lunchmoney.app/developers).   **Try it from these docs**  These docs are interactive — use **Test request** on any endpoint to call the API from this page. Choose a LIVE or MOCK service from the Server dropdown. Requests sent to `https://api.lunchmoney.dev/v2` can <span class=\"red-text\"><strong>change or delete</strong></span> your data and are <span class=\"red-text\"><strong>permanent</strong></span>. See the [Getting Started Guide](https://lunchmoney.dev/v2/getting-started) before using the live API.  **Static mock server**  Explore without risk to real data. Select `https://mock.lunchmoney.dev/v2` in the Server dropdown to work with static mock data. POST, PUT, and DELETE requests will return realistic responses, but do not change the mock data.   **Client Libraries & SDKs**  An official TypeScript SDK is available on [NPM](https://www.npmjs.com/package/@lunch-money/v2-api-spec) and [GitHub](https://github.com/lunch-money/lunch-money-js-v2). For Python or other languages, see [lunchmoney-clients](https://github.com/juftin/lunchmoney-clients) or generate a client from [this OpenAPI spec](/v2/openapi).  **Migrating from v1**  The v2 API is not backwards compatible with v1. See the [Migration Guide](https://lunchmoney.dev/v2/migration-guide) for details.  **Useful links** - [Getting Started Guide](https://lunchmoney.dev/v2/getting-started) - [v2 API Overview](https://lunchmoney.dev/v2/overview) - [Version History](https://lunchmoney.dev/v2/version-history) - [Migration Guide](https://lunchmoney.dev/v2/migration-guide) - [Rate Limits](https://lunchmoney.dev/v2/rate-limits)

API version: 2.11.0
Contact: devsupport@lunchmoney.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lunchmoney

import (
	"encoding/json"
)

// checks if the RecurringObjectOverrides type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecurringObjectOverrides{}

// RecurringObjectOverrides The values that will be applied to matching transactions.
type RecurringObjectOverrides struct {
	// If present, the payee name that will be displayed for any matching transactions.
	Payee *string `json:"payee,omitempty"`
	// If present, the notes that will be displayed for any matching transactions.
	Notes *string `json:"notes,omitempty"`
	// If present, the ID of the category that matching transactions will be assigned to.
	CategoryId *int32 `json:"category_id,omitempty"`
}

// NewRecurringObjectOverrides instantiates a new RecurringObjectOverrides object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecurringObjectOverrides() *RecurringObjectOverrides {
	this := RecurringObjectOverrides{}
	return &this
}

// NewRecurringObjectOverridesWithDefaults instantiates a new RecurringObjectOverrides object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecurringObjectOverridesWithDefaults() *RecurringObjectOverrides {
	this := RecurringObjectOverrides{}
	return &this
}

// GetPayee returns the Payee field value if set, zero value otherwise.
func (o *RecurringObjectOverrides) GetPayee() string {
	if o == nil || IsNil(o.Payee) {
		var ret string
		return ret
	}
	return *o.Payee
}

// GetPayeeOk returns a tuple with the Payee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecurringObjectOverrides) GetPayeeOk() (*string, bool) {
	if o == nil || IsNil(o.Payee) {
		return nil, false
	}
	return o.Payee, true
}

// HasPayee returns a boolean if a field has been set.
func (o *RecurringObjectOverrides) HasPayee() bool {
	if o != nil && !IsNil(o.Payee) {
		return true
	}

	return false
}

// SetPayee gets a reference to the given string and assigns it to the Payee field.
func (o *RecurringObjectOverrides) SetPayee(v string) {
	o.Payee = &v
}

// GetNotes returns the Notes field value if set, zero value otherwise.
func (o *RecurringObjectOverrides) GetNotes() string {
	if o == nil || IsNil(o.Notes) {
		var ret string
		return ret
	}
	return *o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecurringObjectOverrides) GetNotesOk() (*string, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *RecurringObjectOverrides) HasNotes() bool {
	if o != nil && !IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given string and assigns it to the Notes field.
func (o *RecurringObjectOverrides) SetNotes(v string) {
	o.Notes = &v
}

// GetCategoryId returns the CategoryId field value if set, zero value otherwise.
func (o *RecurringObjectOverrides) GetCategoryId() int32 {
	if o == nil || IsNil(o.CategoryId) {
		var ret int32
		return ret
	}
	return *o.CategoryId
}

// GetCategoryIdOk returns a tuple with the CategoryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecurringObjectOverrides) GetCategoryIdOk() (*int32, bool) {
	if o == nil || IsNil(o.CategoryId) {
		return nil, false
	}
	return o.CategoryId, true
}

// HasCategoryId returns a boolean if a field has been set.
func (o *RecurringObjectOverrides) HasCategoryId() bool {
	if o != nil && !IsNil(o.CategoryId) {
		return true
	}

	return false
}

// SetCategoryId gets a reference to the given int32 and assigns it to the CategoryId field.
func (o *RecurringObjectOverrides) SetCategoryId(v int32) {
	o.CategoryId = &v
}

func (o RecurringObjectOverrides) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecurringObjectOverrides) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Payee) {
		toSerialize["payee"] = o.Payee
	}
	if !IsNil(o.Notes) {
		toSerialize["notes"] = o.Notes
	}
	if !IsNil(o.CategoryId) {
		toSerialize["category_id"] = o.CategoryId
	}
	return toSerialize, nil
}

type NullableRecurringObjectOverrides struct {
	value *RecurringObjectOverrides
	isSet bool
}

func (v NullableRecurringObjectOverrides) Get() *RecurringObjectOverrides {
	return v.value
}

func (v *NullableRecurringObjectOverrides) Set(val *RecurringObjectOverrides) {
	v.value = val
	v.isSet = true
}

func (v NullableRecurringObjectOverrides) IsSet() bool {
	return v.isSet
}

func (v *NullableRecurringObjectOverrides) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecurringObjectOverrides(val *RecurringObjectOverrides) *NullableRecurringObjectOverrides {
	return &NullableRecurringObjectOverrides{value: val, isSet: true}
}

func (v NullableRecurringObjectOverrides) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecurringObjectOverrides) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


