/*
Lunch Money API - v2

Welcome to the Lunch Money v2 API. The API is available at `https://api.lunchmoney.dev/v2`. Get your access token from the [Lunch Money developers page](https://my.lunchmoney.app/developers).  ### Introduction  <span class=\"red-text\"><strong>The v2 API is in open alpha and is still subject to change. Use the mock server or a test budget when getting started.</strong></span>  **Static Mock Server**  Explore the API without an access token or risk to real data. Select **\"Static Mock v2 Lunch Money API Server\"** from the Server dropdown, then set your Bearer token to any string with 11 or more characters.  **Migrating from v1**  The v2 API is not backwards compatible with v1. See the [Migration Guide](https://alpha.lunchmoney.dev/v2/migration-guide) for details.  **Useful links** - [Developer Portal](https://lunchmoney.dev/v2/introduction) - [Getting Started Guide](https://lunchmoney.dev/v2/getting-started) - [v2 API Overview](https://lunchmoney.dev/v2/overview) - [v2 API Changelog](https://lunchmoney.dev/v2/changelog) - [Migration Guide](https://lunchmoney.dev/v2/migration-guide) - [Rate Limits](https://lunchmoney.dev/v2/rate-limits)

API version: 2.9.4
Contact: devsupport@lunchmoney.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lunchmoney

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SummaryRecurringTransactionObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SummaryRecurringTransactionObject{}

// SummaryRecurringTransactionObject A single transaction associated with a recurring item. I don't think we will expose this in the summary since it's gettable by querying the recurring_id
type SummaryRecurringTransactionObject struct {
	Date string `json:"date"`
	CategoryId int32 `json:"category_id"`
	Payee string `json:"payee"`
	ToBase float32 `json:"to_base"`
	Amount string `json:"amount"`
	Currency CurrencyEnum `json:"currency"`
}

type _SummaryRecurringTransactionObject SummaryRecurringTransactionObject

// NewSummaryRecurringTransactionObject instantiates a new SummaryRecurringTransactionObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSummaryRecurringTransactionObject(date string, categoryId int32, payee string, toBase float32, amount string, currency CurrencyEnum) *SummaryRecurringTransactionObject {
	this := SummaryRecurringTransactionObject{}
	this.Date = date
	this.CategoryId = categoryId
	this.Payee = payee
	this.ToBase = toBase
	this.Amount = amount
	this.Currency = currency
	return &this
}

// NewSummaryRecurringTransactionObjectWithDefaults instantiates a new SummaryRecurringTransactionObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSummaryRecurringTransactionObjectWithDefaults() *SummaryRecurringTransactionObject {
	this := SummaryRecurringTransactionObject{}
	return &this
}

// GetDate returns the Date field value
func (o *SummaryRecurringTransactionObject) GetDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Date
}

// GetDateOk returns a tuple with the Date field value
// and a boolean to check if the value has been set.
func (o *SummaryRecurringTransactionObject) GetDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Date, true
}

// SetDate sets field value
func (o *SummaryRecurringTransactionObject) SetDate(v string) {
	o.Date = v
}

// GetCategoryId returns the CategoryId field value
func (o *SummaryRecurringTransactionObject) GetCategoryId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CategoryId
}

// GetCategoryIdOk returns a tuple with the CategoryId field value
// and a boolean to check if the value has been set.
func (o *SummaryRecurringTransactionObject) GetCategoryIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CategoryId, true
}

// SetCategoryId sets field value
func (o *SummaryRecurringTransactionObject) SetCategoryId(v int32) {
	o.CategoryId = v
}

// GetPayee returns the Payee field value
func (o *SummaryRecurringTransactionObject) GetPayee() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Payee
}

// GetPayeeOk returns a tuple with the Payee field value
// and a boolean to check if the value has been set.
func (o *SummaryRecurringTransactionObject) GetPayeeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Payee, true
}

// SetPayee sets field value
func (o *SummaryRecurringTransactionObject) SetPayee(v string) {
	o.Payee = v
}

// GetToBase returns the ToBase field value
func (o *SummaryRecurringTransactionObject) GetToBase() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ToBase
}

// GetToBaseOk returns a tuple with the ToBase field value
// and a boolean to check if the value has been set.
func (o *SummaryRecurringTransactionObject) GetToBaseOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ToBase, true
}

// SetToBase sets field value
func (o *SummaryRecurringTransactionObject) SetToBase(v float32) {
	o.ToBase = v
}

// GetAmount returns the Amount field value
func (o *SummaryRecurringTransactionObject) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *SummaryRecurringTransactionObject) GetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *SummaryRecurringTransactionObject) SetAmount(v string) {
	o.Amount = v
}

// GetCurrency returns the Currency field value
func (o *SummaryRecurringTransactionObject) GetCurrency() CurrencyEnum {
	if o == nil {
		var ret CurrencyEnum
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *SummaryRecurringTransactionObject) GetCurrencyOk() (*CurrencyEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *SummaryRecurringTransactionObject) SetCurrency(v CurrencyEnum) {
	o.Currency = v
}

func (o SummaryRecurringTransactionObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SummaryRecurringTransactionObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["date"] = o.Date
	toSerialize["category_id"] = o.CategoryId
	toSerialize["payee"] = o.Payee
	toSerialize["to_base"] = o.ToBase
	toSerialize["amount"] = o.Amount
	toSerialize["currency"] = o.Currency
	return toSerialize, nil
}

func (o *SummaryRecurringTransactionObject) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"date",
		"category_id",
		"payee",
		"to_base",
		"amount",
		"currency",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSummaryRecurringTransactionObject := _SummaryRecurringTransactionObject{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSummaryRecurringTransactionObject)

	if err != nil {
		return err
	}

	*o = SummaryRecurringTransactionObject(varSummaryRecurringTransactionObject)

	return err
}

type NullableSummaryRecurringTransactionObject struct {
	value *SummaryRecurringTransactionObject
	isSet bool
}

func (v NullableSummaryRecurringTransactionObject) Get() *SummaryRecurringTransactionObject {
	return v.value
}

func (v *NullableSummaryRecurringTransactionObject) Set(val *SummaryRecurringTransactionObject) {
	v.value = val
	v.isSet = true
}

func (v NullableSummaryRecurringTransactionObject) IsSet() bool {
	return v.isSet
}

func (v *NullableSummaryRecurringTransactionObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSummaryRecurringTransactionObject(val *SummaryRecurringTransactionObject) *NullableSummaryRecurringTransactionObject {
	return &NullableSummaryRecurringTransactionObject{value: val, isSet: true}
}

func (v NullableSummaryRecurringTransactionObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSummaryRecurringTransactionObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


