# coding: utf-8

"""
    Lunch Money API - v2

    ### Introduction  Welcome to the Lunch Money v2 API reference. This is the **v2.11.1** spec.  The API is available at `https://api.lunchmoney.dev/v2`. Get your access token from the [Lunch Money developers page](https://my.lunchmoney.app/developers).   **Try it from these docs**  These docs are interactive — use **Test request** on any endpoint to call the API from this page. Choose a LIVE or MOCK service from the Server dropdown. Requests sent to `https://api.lunchmoney.dev/v2` can <span class=\"red-text\"><strong>change or delete</strong></span> your data and are <span class=\"red-text\"><strong>permanent</strong></span>. See the [Getting Started Guide](https://lunchmoney.dev/v2/getting-started) before using the live API.  **Static mock server**  Explore without risk to real data. Select `https://mock.lunchmoney.dev/v2` in the Server dropdown to work with static mock data. POST, PUT, and DELETE requests will return realistic responses, but do not change the mock data.   **Client Libraries & SDKs**  An official TypeScript SDK is available on [NPM](https://www.npmjs.com/package/@lunch-money/v2-api-spec) and [GitHub](https://github.com/lunch-money/lunch-money-js-v2). For Python or other languages, see [lunchmoney-clients](https://github.com/juftin/lunchmoney-clients) or generate a client from [this OpenAPI spec](/v2/openapi).  **Migrating from v1**  The v2 API is not backwards compatible with v1. See the [Migration Guide](https://lunchmoney.dev/v2/migration-guide) for details.  **Useful links** - [Getting Started Guide](https://lunchmoney.dev/v2/getting-started) - [v2 API Overview](https://lunchmoney.dev/v2/overview) - [Version History](https://lunchmoney.dev/v2/version-history) - [Migration Guide](https://lunchmoney.dev/v2/migration-guide) - [Rate Limits](https://lunchmoney.dev/v2/rate-limits)

    The version of the OpenAPI document: 2.11.1
    Contact: devsupport@lunchmoney.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class LocaleEnum(str, Enum):
    """
    Locale used for formatting numbers and currency amounts in the Lunch Money app.
    """

    """
    allowed enum values
    """
    SQ_MINUS_AL = 'sq-AL'
    BE_MINUS_BY = 'be-BY'
    BG_MINUS_BG = 'bg-BG'
    CA_MINUS_ES = 'ca-ES'
    ZH_MINUS_CN = 'zh-CN'
    ZH_MINUS_HK = 'zh-HK'
    ZH_MINUS_TW = 'zh-TW'
    HR_MINUS_HR = 'hr-HR'
    CS_MINUS_CZ = 'cs-CZ'
    DA_MINUS_DK = 'da-DK'
    NL_MINUS_BE = 'nl-BE'
    NL_MINUS_NL = 'nl-NL'
    EN_MINUS_AU = 'en-AU'
    EN_MINUS_CA = 'en-CA'
    EN_MINUS_IN = 'en-IN'
    EN_MINUS_IE = 'en-IE'
    EN_MINUS_MT = 'en-MT'
    EN_MINUS_NZ = 'en-NZ'
    EN_MINUS_PH = 'en-PH'
    EN_MINUS_SG = 'en-SG'
    EN_MINUS_ZA = 'en-ZA'
    EN_MINUS_GB = 'en-GB'
    EN_MINUS_US = 'en-US'
    ET_MINUS_EE = 'et-EE'
    FI_MINUS_FI = 'fi-FI'
    FR_MINUS_BE = 'fr-BE'
    FR_MINUS_CA = 'fr-CA'
    FR_MINUS_FR = 'fr-FR'
    FR_MINUS_LU = 'fr-LU'
    FR_MINUS_CH = 'fr-CH'
    DE_MINUS_AT = 'de-AT'
    DE_MINUS_DE = 'de-DE'
    DE_MINUS_LU = 'de-LU'
    DE_MINUS_CH = 'de-CH'
    EL_MINUS_CY = 'el-CY'
    EL_MINUS_GR = 'el-GR'
    IW_MINUS_IL = 'iw-IL'
    HI_MINUS_IN = 'hi-IN'
    HU_MINUS_HU = 'hu-HU'
    IS_MINUS_IS = 'is-IS'
    IN_MINUS_ID = 'in-ID'
    GA_MINUS_IE = 'ga-IE'
    IT_MINUS_IT = 'it-IT'
    IT_MINUS_CH = 'it-CH'
    JA_MINUS_JP = 'ja-JP'
    KO_MINUS_KR = 'ko-KR'
    LV_MINUS_LV = 'lv-LV'
    LT_MINUS_LT = 'lt-LT'
    MK_MINUS_MK = 'mk-MK'
    MS_MINUS_MY = 'ms-MY'
    MT_MINUS_MT = 'mt-MT'
    NO_MINUS_NO = 'no-NO'
    PL_MINUS_PL = 'pl-PL'
    PT_MINUS_BR = 'pt-BR'
    PT_MINUS_PT = 'pt-PT'
    RO_MINUS_RO = 'ro-RO'
    RU_MINUS_RU = 'ru-RU'
    SK_MINUS_SK = 'sk-SK'
    SL_MINUS_SI = 'sl-SI'
    ES_MINUS_AR = 'es-AR'
    ES_MINUS_BO = 'es-BO'
    ES_MINUS_CL = 'es-CL'
    ES_MINUS_CO = 'es-CO'
    ES_MINUS_CR = 'es-CR'
    ES_MINUS_DO = 'es-DO'
    ES_MINUS_EC = 'es-EC'
    ES_MINUS_SV = 'es-SV'
    ES_MINUS_GT = 'es-GT'
    ES_MINUS_HN = 'es-HN'
    ES_MINUS_MX = 'es-MX'
    ES_MINUS_NI = 'es-NI'
    ES_MINUS_PA = 'es-PA'
    ES_MINUS_PY = 'es-PY'
    ES_MINUS_PE = 'es-PE'
    ES_MINUS_PR = 'es-PR'
    ES_MINUS_ES = 'es-ES'
    ES_MINUS_US = 'es-US'
    ES_MINUS_UY = 'es-UY'
    ES_MINUS_VE = 'es-VE'
    SV_MINUS_SE = 'sv-SE'
    TH_MINUS_TH = 'th-TH'
    TR_MINUS_TR = 'tr-TR'
    UK_MINUS_UA = 'uk-UA'
    VI_MINUS_VN = 'vi-VN'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of LocaleEnum from a JSON string"""
        return cls(json.loads(json_str))


