# coding: utf-8

"""
    Lunch Money API - v2

    ### Introduction  Welcome to the Lunch Money v2 API reference. This is the **v2.11.0** spec.  The API is available at `https://api.lunchmoney.dev/v2`. Get your access token from the [Lunch Money developers page](https://my.lunchmoney.app/developers).   **Try it from these docs**  These docs are interactive — use **Test request** on any endpoint to call the API from this page. Choose a LIVE or MOCK service from the Server dropdown. Requests sent to `https://api.lunchmoney.dev/v2` can <span class=\"red-text\"><strong>change or delete</strong></span> your data and are <span class=\"red-text\"><strong>permanent</strong></span>. See the [Getting Started Guide](https://lunchmoney.dev/v2/getting-started) before using the live API.  **Static mock server**  Explore without risk to real data. Select `https://mock.lunchmoney.dev/v2` in the Server dropdown to work with static mock data. POST, PUT, and DELETE requests will return realistic responses, but do not change the mock data.   **Client Libraries & SDKs**  An official TypeScript SDK is available on [NPM](https://www.npmjs.com/package/@lunch-money/v2-api-spec) and [GitHub](https://github.com/lunch-money/lunch-money-js-v2). For Python or other languages, see [lunchmoney-clients](https://github.com/juftin/lunchmoney-clients) or generate a client from [this OpenAPI spec](/v2/openapi).  **Migrating from v1**  The v2 API is not backwards compatible with v1. See the [Migration Guide](https://lunchmoney.dev/v2/migration-guide) for details.  **Useful links** - [Getting Started Guide](https://lunchmoney.dev/v2/getting-started) - [v2 API Overview](https://lunchmoney.dev/v2/overview) - [Version History](https://lunchmoney.dev/v2/version-history) - [Migration Guide](https://lunchmoney.dev/v2/migration-guide) - [Rate Limits](https://lunchmoney.dev/v2/rate-limits)

    The version of the OpenAPI document: 2.11.0
    Contact: devsupport@lunchmoney.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from lunchmoney.models.create_category_request_object_children_inner import CreateCategoryRequestObjectChildrenInner
from typing import Optional, Set
from typing_extensions import Self

class UpdateCategoryRequestObject(BaseModel):
    """
    UpdateCategoryRequestObject
    """ # noqa: E501
    name: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=100)]] = Field(default=None, description="If set, updates the category name. Must be between 1 and 100 characters.")
    description: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=200)]] = Field(default=None, description="If set, updates the category description. Must not exceed 200 characters.")
    is_income: Optional[StrictBool] = Field(default=None, description="If set, determines whether transactions in this category are treated as income. (See [Category Properties](https://support.lunchmoney.app/setup/categories/category-properties) for details)")
    exclude_from_budget: Optional[StrictBool] = Field(default=None, description="If set, determines whether transactions in this category are excluded from budgets. (See [Category Properties](https://support.lunchmoney.app/setup/categories/category-properties) for details)")
    exclude_from_totals: Optional[StrictBool] = Field(default=None, description="If set, determines whether transactions in this category are excluded from totals. (See [Category Properties](https://support.lunchmoney.app/setup/categories/category-properties) for details)")
    archived: Optional[StrictBool] = Field(default=None, description="If set, determines whether this category is archived.")
    group_id: Optional[StrictInt] = Field(default=None, description="If set to the ID of an existing category group, and this category is not itself a category group, this category will be assigned to that group.")
    is_group: Optional[StrictBool] = Field(default=False, description="This property is tolerated but cannot be changed. This API cannot be used to convert a category into a category group or vice versa.")
    children: Optional[List[CreateCategoryRequestObjectChildrenInner]] = Field(default=None, description="List of existing category objects, existing category IDs, or names of new categories to add to the category group. This attribute should only be set when modifying an existing category group.<br> Categories or IDs must already exist and must not already belong to a category group. Categories that already belong to another category group will be moved. If strings are specified, they will be used as names for new categories added to the group. The request will fail if any provided name matches an existing category name.<br> You may mix full category objects, IDs, and new category names in the same request.")
    order: Optional[StrictInt] = Field(default=None, description="Position of the category on the categories page in the Lunch Money app. For categories within a category group, the order is relative to the other categories in the group.<br>While this property can be set via the API, it is generally managed by the user in the Lunch Money app.")
    collapsed: Optional[StrictBool] = Field(default=None, description="If `true`, the category is collapsed in the Lunch Money app.<br>While this property can be set via the API it is generally set by the user in the Lunch Money app.")
    id: Optional[StrictInt] = Field(default=None, description="System defined unique identifier for the category. Ignored if set.")
    archived_at: Optional[datetime] = Field(default=None, description="System set date and time of when the category was last archived (in the ISO 8601 extended format). Provide an ISO 8601 extended datetime or `null` to clear it.")
    updated_at: Optional[datetime] = Field(default=None, description="System set date and time of when the category was last updated (in the ISO 8601 extended format). Ignored if set.")
    created_at: Optional[datetime] = Field(default=None, description="System set date and time of when the category was created (in the ISO 8601 extended format). Ignored if set.")
    __properties: ClassVar[List[str]] = ["name", "description", "is_income", "exclude_from_budget", "exclude_from_totals", "archived", "group_id", "is_group", "children", "order", "collapsed", "id", "archived_at", "updated_at", "created_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateCategoryRequestObject from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in children (list)
        _items = []
        if self.children:
            for _item_children in self.children:
                if _item_children:
                    _items.append(_item_children.to_dict())
            _dict['children'] = _items
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if group_id (nullable) is None
        # and model_fields_set contains the field
        if self.group_id is None and "group_id" in self.model_fields_set:
            _dict['group_id'] = None

        # set to None if is_group (nullable) is None
        # and model_fields_set contains the field
        if self.is_group is None and "is_group" in self.model_fields_set:
            _dict['is_group'] = None

        # set to None if order (nullable) is None
        # and model_fields_set contains the field
        if self.order is None and "order" in self.model_fields_set:
            _dict['order'] = None

        # set to None if collapsed (nullable) is None
        # and model_fields_set contains the field
        if self.collapsed is None and "collapsed" in self.model_fields_set:
            _dict['collapsed'] = None

        # set to None if archived_at (nullable) is None
        # and model_fields_set contains the field
        if self.archived_at is None and "archived_at" in self.model_fields_set:
            _dict['archived_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateCategoryRequestObject from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "description": obj.get("description"),
            "is_income": obj.get("is_income"),
            "exclude_from_budget": obj.get("exclude_from_budget"),
            "exclude_from_totals": obj.get("exclude_from_totals"),
            "archived": obj.get("archived"),
            "group_id": obj.get("group_id"),
            "is_group": obj.get("is_group") if obj.get("is_group") is not None else False,
            "children": [CreateCategoryRequestObjectChildrenInner.from_dict(_item) for _item in obj["children"]] if obj.get("children") is not None else None,
            "order": obj.get("order"),
            "collapsed": obj.get("collapsed"),
            "id": obj.get("id"),
            "archived_at": obj.get("archived_at"),
            "updated_at": obj.get("updated_at"),
            "created_at": obj.get("created_at")
        })
        return _obj


