# coding: utf-8

"""
    Lunch Money API - v2

    ### Introduction  Welcome to the Lunch Money v2 API reference. This is the **v2.11.1** spec.  The API is available at `https://api.lunchmoney.dev/v2`. Get your access token from the [Lunch Money developers page](https://my.lunchmoney.app/developers).   **Try it from these docs**  These docs are interactive — use **Test request** on any endpoint to call the API from this page. Choose a LIVE or MOCK service from the Server dropdown. Requests sent to `https://api.lunchmoney.dev/v2` can <span class=\"red-text\"><strong>change or delete</strong></span> your data and are <span class=\"red-text\"><strong>permanent</strong></span>. See the [Getting Started Guide](https://lunchmoney.dev/v2/getting-started) before using the live API.  **Static mock server**  Explore without risk to real data. Select `https://mock.lunchmoney.dev/v2` in the Server dropdown to work with static mock data. POST, PUT, and DELETE requests will return realistic responses, but do not change the mock data.   **Client Libraries & SDKs**  An official TypeScript SDK is available on [NPM](https://www.npmjs.com/package/@lunch-money/v2-api-spec) and [GitHub](https://github.com/lunch-money/lunch-money-js-v2). For Python or other languages, see [lunchmoney-clients](https://github.com/juftin/lunchmoney-clients) or generate a client from [this OpenAPI spec](/v2/openapi).  **Migrating from v1**  The v2 API is not backwards compatible with v1. See the [Migration Guide](https://lunchmoney.dev/v2/migration-guide) for details.  **Useful links** - [Getting Started Guide](https://lunchmoney.dev/v2/getting-started) - [v2 API Overview](https://lunchmoney.dev/v2/overview) - [Version History](https://lunchmoney.dev/v2/version-history) - [Migration Guide](https://lunchmoney.dev/v2/migration-guide) - [Rate Limits](https://lunchmoney.dev/v2/rate-limits)

    The version of the OpenAPI document: 2.11.1
    Contact: devsupport@lunchmoney.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class MonthDayFormatEnum(str, Enum):
    """
    Format string for displaying month and day values without a year.
    """

    """
    allowed enum values
    """
    MMM_D = 'MMM D'
    MMM_DD = 'MMM DD'
    D_MMM = 'D MMM'
    DD_MMM = 'DD MMM'
    MM_D = 'MM D'
    MM_MINUS_D = 'MM-D'
    MM_DOT_D = 'MM.D'
    MM_SLASH_D = 'MM/D'
    MM_DD = 'MM DD'
    MM_MINUS_DD = 'MM-DD'
    MM_DOT_DD = 'MM.DD'
    MM_SLASH_DD = 'MM/DD'
    M_D = 'M D'
    M_MINUS_D = 'M-D'
    M_DOT_D = 'M.D'
    M_SLASH_D = 'M/D'
    M_DD = 'M DD'
    M_MINUS_DD = 'M-DD'
    M_DOT_DD = 'M.DD'
    M_SLASH_DD = 'M/DD'
    D_MM = 'D MM'
    D_MINUS_MM = 'D-MM'
    D_DOT_MM = 'D.MM'
    D_SLASH_MM = 'D/MM'
    DD_MM = 'DD MM'
    DD_MINUS_MM = 'DD-MM'
    DD_DOT_MM = 'DD.MM'
    DD_SLASH_MM = 'DD/MM'
    D_M = 'D M'
    D_MINUS_M = 'D-M'
    D_DOT_M = 'D.M'
    D_SLASH_M = 'D/M'
    DD_M = 'DD M'
    DD_MINUS_M = 'DD-M'
    DD_DOT_M = 'DD.M'
    DD_SLASH_M = 'DD/M'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MonthDayFormatEnum from a JSON string"""
        return cls(json.loads(json_str))


